export const topTechnicalSkills = [
  { title: "Node.js" },
  { title: "React" },
  { title: "JavaScript" },
  { title: "TypeScript" },
  { title: "HTML" },
  { title: "CSS" },
  { title: "MongoDB" },
  { title: "Express.js" },
  { title: "Angular" },
  { title: "Vue.js" },
  { title: "Python" },
  { title: "Django" },
  { title: "Flask" },
  { title: "Java" },
  { title: "Spring Framework" },
  { title: "C#" },
  { title: ".NET" },
  { title: "Ruby" },
  { title: "PHP" },
  { title: "Laravel" },
  { title: "MySQL" },
  { title: "PostgreSQL" },
  { title: "Git" },
  { title: "RESTful API Design" },
  { title: "GraphQL" },
  { title: "Docker" },
  { title: "Kubernetes" },
  { title: "AWS" },
  { title: "Azure" },
  { title: "Jenkins" },
  { title: "Ruby" },
  { title: "Agile Development" },
  { title: "Scrum" },
  { title: "Kanban" },
  { title: "Jira" },
  { title: "Confluence" },
];
